[package]
name = "horticulteur"
description = "A RFC4180-compliant CSV parsing library"
license = "MIT"
version = "1.1.0"
authors = ["Clément Sibille <clement.sibille@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
